In [3]:
import torch
x = torch.arange(12)
y = x.reshape(3, 4)
print(y)

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])


In [5]:
import torch
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
x = torch.arange(12).to(device)
print(x)
print(x.shape)
print(x.ndim)
print(x.dtype)
print(x.device)
print(x.requires_grad)
print(x.grad)
print(x.grad_fn)
print(x.grad_fn)

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11], device='cuda:0')
torch.Size([12])
1
torch.int64
cuda:0
False
None
None
None


In [4]:
import torch
x = torch.arange(12, dtype=torch.float32)
x.requires_grad = True
x.grad
x.numel()
x.exp()

tensor([1.0000e+00, 2.7183e+00, 7.3891e+00, 2.0086e+01, 5.4598e+01, 1.4841e+02,
        4.0343e+02, 1.0966e+03, 2.9810e+03, 8.1031e+03, 2.2026e+04, 5.9874e+04],
       grad_fn=<ExpBackward0>)