Demo to use some functions in torch

In [8]:
import torch
import torch.nn.functional as F
a = torch.rand([3, 3, ])
print(a.view(-1))
# convert the distribution to a probability distribution, means all items add up to 1
norm = F.softmax(a, dim=0)
print(norm)

tensor([0.9554, 0.2879, 0.6005, 0.8414, 0.9428, 0.8068, 0.7720, 0.2901, 0.3561])
tensor([[0.3670, 0.2546, 0.3320],
        [0.3275, 0.4902, 0.4080],
        [0.3055, 0.2552, 0.2600]])


In [ ]:
import torch 
a = torch.randn(10, requires_grad=True)
b = a ** 2
b.backward(grad=torch.ones_like(b))
a.grad

tensor([3.3570, 0.1253, 2.3570, 0.1332, 0.2340, 1.1473, 0.0561, 1.8408, 0.2787,
        0.6315], grad_fn=<PowBackward0>)
tensor([3.6644, -0.0000, -0.0000, -0.0000, -0.0000, -0.0000, -0.0000, -0.0000, -0.0000,
        -0.0000])


AttributeError: 'Tensor' object has no attribute 'zero_grad'